name: buffywalls_3
description: A Wallpaper app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.11+12

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.3+1
  icons_launcher: ^2.0.4
  provider: ^6.0.3
  cached_network_image: ^3.2.1
  change_app_package_name: ^1.1.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  fluttericon: ^2.0.0
  shared_preferences: ^2.0.15
  animated_bottom_navigation_bar: ^1.0.1
  flutter_zoom_drawer: ^3.0.2
  flutter_spinkit: ^5.1.0
  lottie: ^1.3.0
  double_back_to_close_app: ^2.1.0
  card_swiper: ^2.0.4
  flutter_staggered_grid_view: ^0.6.1
  palette_generator: ^0.3.3+1
  flutter_cache_manager: ^3.3.0
  wallpaper_manager_flutter: ^0.0.2
  dio: ^4.0.6
  external_path: ^1.0.1
  permission_handler: ^10.0.0
  top_snackbar_flutter: ^2.1.1
  url_launcher: ^6.1.3
  open_filex: ^4.2.2
  share_plus: ^6.0.1
  package_info_plus: ^1.4.2
  connectivity_plus: ^3.0.2
  new_version_plus: ^0.0.3
  awesome_notifications: ^0.7.4
  get_storage: ^2.0.3
  flex_color_picker: ^2.5.0
  image_picker: ^0.8.5+3
  firebase_storage: ^11.0.2
  firebase_core: ^2.1.0
  firebase_messaging: ^14.0.2
  flutter_onboarding_slider: ^1.0.7
  blobs: ^2.0.0
  google_mobile_ads: ^2.1.0
  is_pirated: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/Dev/
    - assets/Loading/
    - assets/Pro Dialog/
    - assets/onBoard/
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: font/icons.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
